In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('netflix_titles.csv')

In [4]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [6]:
df.shape

(8807, 12)

Level 1 – Beginner
Load the dataset.
Display the first 10 rows.
Display the last 10 rows.
Find the number of rows and columns.
Display all column names.
Check the data types.
Display summary statistics.
Find missing values in each column.
Count total Movies and TV Shows.
Display only the title column.

In [7]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [8]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [9]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [10]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [11]:
df.value_counts("type")

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [12]:
df["title"]

0        Dick Johnson Is Dead
1               Blood & Water
2                   Ganglands
3       Jailbirds New Orleans
4                Kota Factory
                ...
8802                   Zodiac
8803              Zombie Dumb
8804               Zombieland
8805                     Zoom
8806                   Zubaan
Name: title, Length: 8807, dtype: object

🟡 Level 2 – Filtering
Display only Movies.
Display only TV Shows.
Find all movies released after 2020.
Find all TV Shows released after 2018.
Display all content from India.
Display all content from the United States.
Find content with rating TV-MA.
Find content with rating PG-13.
Find movies added in 2021.
Find TV Shows added in 2020.

In [13]:
df[df["type"] == "Movie"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [14]:
df[df["type"]=="TV Show"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...,...
8795,s8796,TV Show,Yu-Gi-Oh! Arc-V,NaN,"Mike Liscio, Emily Bauer, Billy Bob Thompson, ...","Japan, Canada","May 1, 2018",2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Now that he's discovered the Pendulum Summonin...
8796,s8797,TV Show,Yunus Emre,NaN,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
8797,s8798,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
8800,s8801,TV Show,Zindagi Gulzar Hai,NaN,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,"December 15, 2016",2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."

In [15]:
df[(df["type"]=="Movie") & (df["release_year"]>2020)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
13,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...
18,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,Thrillers,After a deadly home invasion at a couple’s new...
...,...,...,...,...,...,...,...,...,...,...,...,...
1425,s1426,Movie,Creating The Queen's Gambit,NaN,NaN,United States,"January 8, 2021",2021,TV-14,14 min,Documentaries,A fascinating character. Exquisite sets. A wig...
1431,s1432,Movie,Stuck Apart,NaN,"Engin Günaydın, Haluk Bilginer, Binnur Kaya, Ö...",Turkey,"January 8, 2021",2021,TV-MA,97 min,"Comedies, Dramas, International Movies","Entrenched in a midlife crisis, Aziz seeks sol..."
1436,s1437,Movie,Ratones Paranoicos: The Band that Rocked Argen...,"Alejandro Ruax, Ramiro Martínez","Juan Sebastián Gutiérrez, Pablo Cano, Pablo Me...",NaN,"January 6, 2021",2021,TV-MA,76 min,"Documentaries, International Movies, Music & M...","The irrepressible Ratones Paranoicos, Argentin..."
1466,s1467,Movie,The Minimalists: Less Is Now,NaN,NaN,United States,"January 1, 2021",2021,TV-14,54 min,Documentaries,They've built a movement out of minimalism. Lo...
1468,s1469,Movie,What Happened to Mr. Cha?,Kim Dong-kyu,"Cha In-pyo, Cho Dal-hwan, Song Jae-ryong",South Korea,"January 1, 2021",2021,TV-MA,102 min,"Comedies, International Movies","With the peak of his career long behind him, a..."

In [16]:
df[(df["type"]=="TV Show") & (df["release_year"]>2020)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,s1461,TV Show,Monarca,NaN,"Irene Azuela, Juan Manuel Bernal, Osvaldo Bena...",Mexico,"January 1, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...","After 20 years, Ana María returns to Mexico an..."
1551,s1552,TV Show,Hilda,NaN,"Bella Ramsey, Ameerah Falzon-Ojo, Oliver Nelso...","United Kingdom, Canada, United States","December 14, 2020",2021,TV-Y7,2 Seasons,Kids' TV,"Fearless, free-spirited Hilda finds new friend..."
1696,s1697,TV Show,Polly Pocket,NaN,"Emily Tennant, Shannon Chan-Kent, Kazumi Evans...","Canada, United States, Ireland","November 15, 2020",2021,TV-Y,2 Seasons,Kids' TV,After uncovering a magical locket that allows ...
2920,s2921,TV Show,Love Is Blind,NaN,"Nick Lachey, Vanessa Lachey",United States,"February 13, 2020",2021,TV-MA,1 Season,"Reality TV, Romantic TV Shows",Nick and Vanessa Lachey host this social exper...
8437,s8438,TV Show,The Netflix Afterparty,NaN,"David Spade, London Hughes, Fortune Feimster",United States,"January 2, 2021",2021,TV-MA,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies","Hosts David Spade, Fortune Feimster and London..."

In [17]:
df[df["country"]=="India"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
39,s40,TV Show,Chhota Bheem,NaN,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",India,"September 16, 2021",2021,TV-Y7,3 Seasons,Kids' TV,"A brave, energetic little boy with superhuman ..."
50,s51,TV Show,Dharmakshetra,NaN,"Kashmira Irani, Chandan Anand, Dinesh Mehta, A...",India,"September 15, 2021",2014,TV-PG,1 Season,"International TV Shows, TV Dramas, TV Sci-Fi &...","After the ancient Great War, the god Chitragup..."
66,s67,TV Show,Raja Rasoi Aur Anya Kahaniyan,NaN,NaN,India,"September 15, 2021",2014,TV-G,1 Season,"Docuseries, International TV Shows",Explore the history and flavors of regional In...
...,...,...,...,...,...,...,...,...,...,...,...,...
8773,s8774,Movie,Yanda Kartavya Aahe,Kedar Shinde,"Ankush Choudhary, Smita Shewale, Mohan Joshi, ...",India,"January 1, 2018",2006,TV-PG,151 min,"Comedies, Dramas, International Movies",Thanks to an arranged marriage that was design...
8775,s8776,TV Show,Yeh Meri Family,NaN,"Vishesh Bansal, Mona Singh, Akarsh Khurana, Ah...",India,"August 31, 2018",2018,TV-PG,1 Season,"International TV Shows, TV Comedies","In the summer of 1998, middle child Harshu bal..."
8798,s8799,Movie,Zed Plus,Chandra Prakash Dwivedi,"Adil Hussain, Mona Singh, K.K. Raina, Sanjay M...",India,"December 31, 2019",2014,TV-MA,131 min,"Comedies, Dramas, International Movies",A philandering small-town mechanic's political...
8799,s8800,Movie,Zenda,Avadhoot Gupte,"Santosh Juvekar, Siddharth Chandekar, Sachit P...",India,"February 15, 2018",2009,TV-14,120 min,"Dramas, International Movies",A change in the leadership of a political part...
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [18]:
df[df["country"]=="United States"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
15,s16,TV Show,Dear White People,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,"September 22, 2021",2021,TV-MA,4 Seasons,"TV Comedies, TV Dramas",Students of color navigate the daily slights a...
27,s28,Movie,Grown Ups,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S...",United States,"September 20, 2021",2010,PG-13,103 min,Comedies,Mourning the loss of their beloved junior high...
28,s29,Movie,Dark Skies,Scott Stewart,"Keri Russell, Josh Hamilton, J.K. Simmons, Dak...",United States,"September 19, 2021",2013,PG-13,97 min,"Horror Movies, Sci-Fi & Fantasy",A family’s idyllic suburban life shatters when...
...,...,...,...,...,...,...,...,...,...,...,...,...
8791,s8792,Movie,Young Adult,Jason Reitman,"Charlize Theron, Patton Oswalt, Patrick Wilson...",United States,"November 20, 2019",2011,R,94 min,"Comedies, Dramas, Independent Movies",When a divorced writer gets a letter from an o...
8793,s8794,Movie,"Yours, Mine and Ours",Raja Gosnell,"Dennis Quaid, Rene Russo, Sean Faris, Katija P...",United States,"November 20, 2019",2005,PG,88 min,"Children & Family Movies, Comedies",When a father of eight and a mother of 10 prep...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."

In [19]:
df[df["rating"]=="TV-MA"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...,...
8762,s8763,Movie,Wrong Side Raju,Mikhil Musale,"Pratik Gandhi, Kimberley Louisa McBeath, Asif ...",India,"October 1, 2017",2016,TV-MA,140 min,"Dramas, International Movies",The life of a chauffeur and part-time bootlegg...
8769,s8770,Movie,Y.M.I.: Yeh Mera India,N. Chandra,"Anupam Kher, Atul Kulkarni, Aakash Pandey, Mil...",India,"March 1, 2018",2008,TV-MA,137 min,"Dramas, Independent Movies, International Movies","The lives of a middle-aged soap opera addict, ..."
8788,s8789,Movie,You Carry Me,Ivona Juka,"Lana Baric, Vojislav Brajovic, Natasa Janjic, ...","Croatia, Slovenia, Serbia, Montenegro","July 1, 2016",2015,TV-MA,157 min,"Dramas, International Movies","A soap opera producer, director and makeup art..."
8798,s8799,Movie,Zed Plus,Chandra Prakash Dwivedi,"Adil Hussain, Mona Singh, K.K. Raina, Sanjay M...",India,"December 31, 2019",2014,TV-MA,131 min,"Comedies, Dramas, International Movies",A philandering small-town mechanic's political...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...

In [20]:
df[df["rating"]=="PG-13"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
27,s28,Movie,Grown Ups,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S...",United States,"September 20, 2021",2010,PG-13,103 min,Comedies,Mourning the loss of their beloved junior high...
28,s29,Movie,Dark Skies,Scott Stewart,"Keri Russell, Josh Hamilton, J.K. Simmons, Dak...",United States,"September 19, 2021",2013,PG-13,97 min,"Horror Movies, Sci-Fi & Fantasy",A family’s idyllic suburban life shatters when...
29,s30,Movie,Paranoia,Robert Luketic,"Liam Hemsworth, Gary Oldman, Amber Heard, Harr...","United States, India, France","September 19, 2021",2013,PG-13,106 min,Thrillers,"Blackmailed by his company's CEO, a low-level ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8757,s8758,Movie,World Trade Center,Oliver Stone,"Nicolas Cage, Michael Peña, Maggie Gyllenhaal,...",United States,"November 20, 2019",2006,PG-13,129 min,"Action & Adventure, Dramas","Working under treacherous conditions, an army ..."
8764,s8765,Movie,Wyatt Earp,Lawrence Kasdan,"Kevin Costner, Dennis Quaid, Gene Hackman, Dav...",United States,"January 1, 2020",1994,PG-13,191 min,Action & Adventure,Legendary lawman Wyatt Earp is continually at ...
8766,s8767,Movie,XXx,Rob Cohen,"Vin Diesel, Asia Argento, Marton Csokas, Samue...",United States,"January 1, 2019",2002,PG-13,124 min,"Action & Adventure, Sports Movies",A notorious underground rush-seeker deemed unt...
8767,s8768,Movie,XXX: State of the Union,Lee Tamahori,"Ice Cube, Samuel L. Jackson, Willem Dafoe, Sco...",United States,"January 1, 2019",2005,PG-13,101 min,Action & Adventure,"In this action-packed follow-up to XXX, U.S. i..."
8782,s8783,Movie,Yoga Hosers,Kevin Smith,"Harley Quinn Smith, Lily-Rose Depp, Johnny Dep...",United States,"December 2, 2016",2016,PG-13,88 min,"Comedies, Horror Movies, Independent Movies",With an all-important high school party at sta...

In [21]:
df[(df["type"]=="Movie") & (df["release_year"]==2021)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
13,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...
18,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,Thrillers,After a deadly home invasion at a couple’s new...
...,...,...,...,...,...,...,...,...,...,...,...,...
1425,s1426,Movie,Creating The Queen's Gambit,NaN,NaN,United States,"January 8, 2021",2021,TV-14,14 min,Documentaries,A fascinating character. Exquisite sets. A wig...
1431,s1432,Movie,Stuck Apart,NaN,"Engin Günaydın, Haluk Bilginer, Binnur Kaya, Ö...",Turkey,"January 8, 2021",2021,TV-MA,97 min,"Comedies, Dramas, International Movies","Entrenched in a midlife crisis, Aziz seeks sol..."
1436,s1437,Movie,Ratones Paranoicos: The Band that Rocked Argen...,"Alejandro Ruax, Ramiro Martínez","Juan Sebastián Gutiérrez, Pablo Cano, Pablo Me...",NaN,"January 6, 2021",2021,TV-MA,76 min,"Documentaries, International Movies, Music & M...","The irrepressible Ratones Paranoicos, Argentin..."
1466,s1467,Movie,The Minimalists: Less Is Now,NaN,NaN,United States,"January 1, 2021",2021,TV-14,54 min,Documentaries,They've built a movement out of minimalism. Lo...
1468,s1469,Movie,What Happened to Mr. Cha?,Kim Dong-kyu,"Cha In-pyo, Cho Dal-hwan, Song Jae-ryong",South Korea,"January 1, 2021",2021,TV-MA,102 min,"Comedies, International Movies","With the peak of his career long behind him, a..."

In [22]:
df[(df["type"]=="TV Show") & (df["release_year"]==2020)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
17,s18,TV Show,Falsa identidad,NaN,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico,"September 22, 2021",2020,TV-MA,2 Seasons,"Crime TV Shows, Spanish-Language TV Shows, TV ...",Strangers Diego and Isabel flee their home in ...
32,s33,TV Show,Sex Education,NaN,"Asa Butterfield, Gillian Anderson, Ncuti Gatwa...",United Kingdom,"September 17, 2021",2020,TV-MA,3 Seasons,"British TV Shows, International TV Shows, TV C...",Insecure Otis has all the answers when it come...
34,s35,TV Show,Tayo and Little Wizards,NaN,"Dami Lee, Jason Lee, Bommie Catherine Han, Jen...",NaN,"September 17, 2021",2020,TV-Y7,1 Season,Kids' TV,Tayo speeds into an adventure when his friends...
47,s48,TV Show,The Smart Money Woman,Bunmi Ajakaiye,"Osas Ighodaro, Ini Dima-Okojie, Kemi Lala Akin...",NaN,"September 16, 2021",2020,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Five glamorous millennials strive for success ...
148,s149,TV Show,HQ Barbers,Gerhard Mostert,"Hakeem Kae-Kazim, Chioma Omeruah, Orukotan Ade...",NaN,"September 1, 2021",2020,TV-14,1 Season,TV Shows,When a family run barber shop in the heart of ...
...,...,...,...,...,...,...,...,...,...,...,...,...
3287,s3288,TV Show,Maradona in Mexico,NaN,Diego Armando Maradona,"Argentina, United States, Mexico","November 13, 2019",2020,TV-MA,1 Season,"Docuseries, Spanish-Language TV Shows","In this docuseries, soccer great Diego Maradon..."
3369,s3370,TV Show,BoJack Horseman,NaN,"Will Arnett, Aaron Paul, Amy Sedaris, Alison B...",United States,"October 25, 2019",2020,TV-MA,6 Seasons,TV Comedies,Meet the most beloved sitcom horse of the '90s...
3433,s3434,TV Show,The Hook Up Plan,NaN,"Marc Ruchmann, Zita Hanrot, Sabrina Ouazani, J...",France,"October 11, 2019",2020,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...","When Parisian Elsa gets hung up on her ex, her..."
8125,s8126,TV Show,Super Wings,NaN,"Luca Padovan, Evan Smolin, Junah Jang, Colin C...","United States, South Korea, China","December 1, 2020",2020,TV-Y,3 Seasons,"Kids' TV, Korean TV Shows",A cheerful jet and his transforming pals striv...
8132,s8133,TV Show,Surviving R. Kelly Part II: The Reckoning,NaN,R. Kelly,United States,"April 13, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries",As more women come forward with harrowing accu...

🟠 Level 3 – Sorting
Sort by release year (ascending).
Sort by release year (descending).
Display the newest movie.
Display the oldest movie.
Display the first 20 movie titles alphabetically.

In [23]:
 df.sort_values(by="release_year")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
...,...,...,...,...,...,...,...,...,...,...,...,...
862,s863,TV Show,Special,NaN,"Ryan O'Connell, Jessica Hecht, Punam Patel, Ma...",United States,"May 20, 2021",2021,TV-MA,2 Seasons,TV Comedies,A young gay man with cerebral palsy branches o...
861,s862,Movie,Little Singham Future mein Satakli,Prakash Satam,"Anamaya Verma, Ganesh Divekar, Jigna Bharadhwa...",NaN,"May 20, 2021",2021,TV-Y7,47 min,"Children & Family Movies, Comedies",Little Singham and his crew travel to the year...
857,s858,TV Show,The Neighbor,NaN,"Quim Gutiérrez, Clara Lago, Adrián Pino, Catel...",Spain,"May 21, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...",Self-centered Javier's life gets a bit messy w...
876,s877,TV Show,Alma Matters,NaN,NaN,India,"May 14, 2021",2021,TV-MA,1 Season,"Docuseries, International TV Shows",Alumni of India’s elite academic institutes sh...
965,s966,TV Show,Yasuke,NaN,"LaKeith Stanfield, Takehiro Hira, Maya Tanida,...",NaN,"April 29, 2021",2021,TV-MA,1 Season,"Anime Series, International TV Shows",A peaceful boatman once known as the Black Sam...

In [24]:
df.sort_values(by="release_year",ascending=False)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
693,s694,Movie,Ali & Ratu Ratu Queens,Lucky Kuswandi,"Iqbaal Ramadhan, Nirina Zubir, Asri Welas, Tik...",NaN,"June 17, 2021",2021,TV-14,101 min,"Comedies, Dramas, International Movies","After his father's passing, a teenager sets ou..."
781,s782,Movie,Black Holes | The Edge of All We Know,Peter Galison,NaN,NaN,"June 2, 2021",2021,TV-14,99 min,Documentaries,Follow scientists on their quest to understand...
762,s763,Movie,Sweet & Sour,Lee Kae-byeok,"Jang Ki-yong, Chae Soo-bin, Jung Soo-jung",South Korea,"June 4, 2021",2021,TV-14,103 min,"Comedies, International Movies, Romantic Movies",Faced with real-world opportunities and challe...
763,s764,TV Show,Sweet Tooth,NaN,"Nonso Anozie, Christian Convery, Adeel Akhtar,...",United States,"June 4, 2021",2021,TV-14,1 Season,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ...",On a perilous adventure across a post-apocalyp...
764,s765,Movie,Trippin' with the Kandasamys,Jayan Moodley,"Jailoshini Naidoo, Maeshni Naicker, Madhushan ...",South Africa,"June 4, 2021",2021,TV-14,94 min,"Comedies, International Movies, Romantic Movies","To rekindle their marriages, best friends-turn..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...

In [25]:
df[df["type"] == "Movie"].sort_values(
    by="release_year",
    ascending=False
).head(1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
570,s571,Movie,Dynasty Warriors,Chow Hin Yeung Roy,"Wang Kai, Louis Koo, Han Geng, Tony Yang, Cari...",NaN,"July 1, 2021",2021,TV-14,118 min,"Action & Adventure, International Movies","Warlords, warriors and statesmen wage a battle..."

In [26]:
df[df["type"] == "Movie"].sort_values(
    by="release_year"
).head(1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...

In [27]:
# Display the first 20 movie titles alphabetically.


df[df["type"] == "Movie"].sort_values(by="title")["title"].head(20)

2036                           #Alive
2304    #AnneFrank - Parallel Stories
2481                #FriendButMarried
2324              #FriendButMarried 2
5973                            #Roxy
5695                        #Rucker50
654                           #Selfie
655                        #Selfie 69
5972                 #cats_the_mewvie
5277                     #realityhigh
306                               '76
5967                              '89
5971                         (T)ERROR
5979                 1 Chance 2 Dance
5980                    1 Mile to You
3392              10 Days in Sun City
5387                   10 jours en or
5981                      10,000 B.C.
5982             100 Days Of Solitude
5577                       100 Meters
Name: title, dtype: object

In [28]:

(df[df["type"] == "Movie"].sort_values(by="title")["title"].head(20)).value_counts().sum()

np.int64(20)

🔵 Level 4 – Analysis
Count Movies and TV Shows.
Count content by rating.
Find the top 10 countries with the most content.
Find the top 10 directors.
Find the top 10 genres (listed_in).
Find the earliest release year.
Find the latest release year.
Find the average release year.
Find the most common rating.
Count how many titles each year.

In [29]:
df.value_counts("type")

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [30]:
df.value_counts("rating")

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
UR             3
NC-17          3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

In [31]:
df.value_counts("country").head(10)

country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Egypt              106
Name: count, dtype: int64

In [32]:
df.value_counts("director").head(10)

director
Rajiv Chilaka             19
Raúl Campos, Jan Suter    18
Suhas Kadav               16
Marcus Raboy              16
Jay Karas                 14
Cathy Garcia-Molina       13
Jay Chapman               12
Youssef Chahine           12
Martin Scorsese           12
Steven Spielberg          11
Name: count, dtype: int64

In [33]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [34]:
df.value_counts("listed_in").head(10)

listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
Kids' TV                                            220
Children & Family Movies                            215
Children & Family Movies, Comedies                  201
Documentaries, International Movies                 186
Dramas, International Movies, Romantic Movies       180
Name: count, dtype: int64

Find the earliest release year.
Find the latest release year.
Find the average release year.
Find the most common rating.
Count how many titles each year.

In [35]:
df.sort_values(by="release_year").head(1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...

In [36]:
df["release_year"].min()

1925

In [37]:
df.sort_values(by="release_year",ascending=False).head(1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
693,s694,Movie,Ali & Ratu Ratu Queens,Lucky Kuswandi,"Iqbaal Ramadhan, Nirina Zubir, Asri Welas, Tik...",NaN,"June 17, 2021",2021,TV-14,101 min,"Comedies, Dramas, International Movies","After his father's passing, a teenager sets ou..."

In [38]:
df["release_year"].max()

2021

In [39]:
df["release_year"].mean()

np.float64(2014.1801975701146)

In [40]:
df["rating"].value_counts().head(1)

rating
TV-MA    3207
Name: count, dtype: int64

In [41]:
df["rating"].mode()

0    TV-MA
Name: rating, dtype: object

In [42]:
df["release_year"].value_counts().sort_index()

release_year
1925       1
1942       2
1943       3
1944       3
1945       4
        ...
2017    1032
2018    1147
2019    1030
2020     953
2021     592
Name: count, Length: 74, dtype: int64

🟣 Level 5 – GroupBy
Count Movies and TV Shows using groupby().
Average release year by type.
Count titles by country.
Count titles by rating.
Count titles by release year.

In [43]:
df.groupby(by="type").size()

type
Movie      6131
TV Show    2676
dtype: int64

In [44]:
df.groupby(by="type")["release_year"].mean()

type
Movie      2013.121514
TV Show    2016.605755
Name: release_year, dtype: float64

In [45]:
df.groupby(by="country").size()

country
, France, Algeria                                       1
, South Korea                                           1
Argentina                                              56
Argentina, Brazil, France, Poland, Germany, Denmark     1
Argentina, Chile                                        2
                                                       ..
Venezuela                                               1
Venezuela, Colombia                                     1
Vietnam                                                 7
West Germany                                            1
Zimbabwe                                                1
Length: 748, dtype: int64

In [46]:
df.groupby(by="rating").size()

rating
66 min         1
74 min         1
84 min         1
G             41
NC-17          3
NR            80
PG           287
PG-13        490
R            799
TV-14       2160
TV-G         220
TV-MA       3207
TV-PG        863
TV-Y         307
TV-Y7        334
TV-Y7-FV       6
UR             3
dtype: int64

In [47]:
df.groupby(by="release_year").size()

release_year
1925       1
1942       2
1943       3
1944       3
1945       4
        ...
2017    1032
2018    1147
2019    1030
2020     953
2021     592
Length: 74, dtype: int64

🔴 Level 6 – Data Cleaning
Remove duplicate rows.
Fill missing values in director with "Unknown".
Fill missing values in country with "Not Available".
Drop rows where date_added is missing.
Check if there are any null values left.

In [48]:
df.drop_duplicates()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [49]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [50]:
df["director"].fillna("unknown")

0       Kirsten Johnson
1               unknown
2       Julien Leclercq
3               unknown
4               unknown
             ...
8802      David Fincher
8803            unknown
8804    Ruben Fleischer
8805       Peter Hewitt
8806        Mozez Singh
Name: director, Length: 8807, dtype: object

In [51]:
df["director"]=df["director"].isnull().sum()

In [52]:
df.isnull().sum()

show_id           0
type              0
title             0
director          0
cast            825
country         831
date_added       10
release_year      0
rating            4
duration          3
listed_in         0
description       0
dtype: int64

In [53]:
df["country"]=df["country"].fillna("not available")

In [54]:
df.isnull().sum()

show_id           0
type              0
title             0
director          0
cast            825
country           0
date_added       10
release_year      0
rating            4
duration          3
listed_in         0
description       0
dtype: int64

In [55]:
df =df.dropna(subset=["date_added"])

In [56]:
df.isnull().sum()

show_id           0
type              0
title             0
director          0
cast            825
country           0
date_added        0
release_year      0
rating            4
duration          3
listed_in         0
description       0
dtype: int64

In [57]:
df=df.dropna(subset=["cast"])

In [58]:
df.shape

(7972, 12)

In [59]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          4
duration        3
listed_in       0
description     0
dtype: int64

In [60]:
df["rating"]=df["rating"].fillna("mean")

In [61]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        3
listed_in       0
description     0
dtype: int64

In [62]:
df["duration"]=df["duration"].fillna("nan")

In [63]:
df["duration"]

1       2 Seasons
2        1 Season
4       2 Seasons
5        1 Season
6          91 min
          ...
8801       96 min
8802      158 min
8804       88 min
8805       88 min
8806      111 min
Name: duration, Length: 7972, dtype: object

In [64]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7972 entries, 1 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7972 non-null   object
 1   type          7972 non-null   object
 2   title         7972 non-null   object
 3   director      7972 non-null   int64
 4   cast          7972 non-null   object
 5   country       7972 non-null   object
 6   date_added    7972 non-null   object
 7   release_year  7972 non-null   int64
 8   rating        7972 non-null   object
 9   duration      7972 non-null   object
 10  listed_in     7972 non-null   object
 11  description   7972 non-null   object
dtypes: int64(2), object(10)
memory usage: 809.7+ KB

🟤 Level 7 – String Operations
Find titles containing "Love".
Find titles containing "King".
Find descriptions containing "family".
Find all movies where the director's name contains "Steven".
Find all content where the country contains "India".

In [66]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,2634,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,2634,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",not available,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
4,s5,TV Show,Kota Factory,2634,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,2634,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",not available,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,2634,"Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",not available,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,2634,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,2634,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,2634,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,2634,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,2634,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [67]:
df[df["title"].str.contains("Love",na=False)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
25,s26,TV Show,Love on the Spectrum,2634,Brooke Satchwell,Australia,"September 21, 2021",2021,TV-14,2 Seasons,"Docuseries, International TV Shows, Reality TV",Finding love can be hard for anyone. For young...
158,s159,Movie,Love Don't Cost a Thing,2634,"Nick Cannon, Christina Milian, Kenan Thompson,...",United States,"September 1, 2021",2003,PG-13,101 min,"Comedies, Romantic Movies",A nerdy teen tries to make himself cool by ass...
159,s160,Movie,Love in a Puff,2634,"Miriam Chin Wah Yeung, Shawn Yue, Singh Hartih...",Hong Kong,"September 1, 2021",2010,TV-MA,103 min,"Comedies, Dramas, International Movies",When the Hong Kong government enacts a ban on ...
206,s207,Movie,"LSD: Love, Sex Aur Dhokha",2634,"Nushrat Bharucha, Anshuman Jha, Neha Chauhan, ...",India,"August 27, 2021",2010,TV-MA,112 min,"Dramas, Independent Movies, International Movies",This provocative drama examines how the voyeur...
227,s228,Movie,Really Love,2634,"Kofi Siriboe, Yootha Wong-Loi-Sing, Michael Ea...",United States,"August 25, 2021",2020,TV-MA,95 min,"Dramas, Independent Movies, Romantic Movies",A rising Black painter tries to break into a c...
...,...,...,...,...,...,...,...,...,...,...,...,...
8567,s8568,TV Show,The Year of Happiness and Love,2634,"Amber Kuo, James Wen, Weber Yang, Sonia Sui, N...",Taiwan,"September 1, 2016",2009,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Jiang Chen-bo is a loser without prospects for...
8575,s8576,TV Show,This Is My Love,2634,"Jin-mo Joo, Sa-rang Kim, Junior, Ja-in Lee, Su...",South Korea,"May 22, 2017",2015,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",A renowned actor who is still pining over the ...
8649,s8650,Movie,Two Lovers and a Bear,2634,"Dane DeHaan, Tatiana Maslany, Gordon Pinsent, ...",Canada,"May 2, 2017",2016,R,95 min,"Dramas, Independent Movies, Romantic Movies",A troubled couple living near the North Pole b...
8721,s8722,TV Show,What Is Love?,2634,"Chris Wu, Jade Chou, Duncan Lai, King Chin, Ki...",Taiwan,"January 1, 2017",2012,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A 32-year-old romantic looking for a long-term...
8725,s8726,Movie,What's Up With Love?,2634,"Dian Sastrowardoyo, Nicholas Saputra, Ladya Ch...",Indonesia,"December 8, 2018",2002,R,110 min,"Dramas, International Movies, Romantic Movies",A popular high school girl strains her relatio...

In [68]:
df[df["title"].str.contains("King",na=True)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
62,s63,Movie,Naruto the Movie 3: Guardians of the Crescent ...,2634,"Junko Takeuchi, Chie Nakamura, Yoichi Masukawa...",Japan,"September 15, 2021",2006,TV-PG,95 min,"Action & Adventure, Anime Features, Internatio...",Exuberant ninja Naruto teams up with his pals ...
73,s74,Movie,King of Boys,2634,"Sola Sobowale, Adesua Etomi, Remilekun ""Remini...",Nigeria,"September 14, 2021",2018,TV-MA,182 min,"Dramas, International Movies",When a powerful businesswoman’s political ambi...
198,s199,TV Show,King of Boys: The Return of the King,2634,"Sola Sobowale, Toni Tones, Richard Mofe-Damijo...",Nigeria,"August 27, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",Alhaja Eniola Salami starts anew and sets her ...
275,s276,TV Show,The Kingdom,2634,"Chino Darín, Nancy Dupláa, Joaquín Furriel, Pe...",Argentina,"August 13, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...","After his running mate's murder, a controversi..."
359,s360,Movie,The Original Kings of Comedy,2634,"Steve Harvey, D.L. Hughley, Cedric the Enterta...",United States,"August 1, 2021",2000,R,111 min,Stand-Up Comedy,"Comedians Steve Harvey, Cedric the Entertainer..."
376,s377,TV Show,Transformers: War for Cybertron: Kingdom,2634,"Jake Foushee, Jason Marnocha, Linsay Rousseau,...",not available,"July 29, 2021",2021,TV-Y7,1 Season,Anime Series,The frantic race to locate the Allspark first ...
398,s399,Movie,Kingdom: Ashin of the North,2634,"Gianna Jun, Park Byung-eun, Kim Si-a, Kim Roi-...",not available,"July 23, 2021",2021,TV-MA,94 min,"Horror Movies, International Movies, Thrillers","Tragedy, betrayal and a mysterious discovery f..."
627,s628,TV Show,The Daily Life of the Immortal King,2634,"Sun Lulu, Qian Chen, Gu Jiangshan",China,"June 30, 2021",2020,TV-14,1 Season,"Anime Series, International TV Shows, Teen TV ...","Having vanquished a powerful demon at age six,..."
780,s781,TV Show,Ben & Holly's Little Kingdom,2634,"Preston Nyman, Sian Taylor, Ian Puleston-Davie...",United Kingdom,"June 2, 2021",2019,TV-Y,2 Seasons,Kids' TV,"In the magical Little Kingdom, friends Ben Elf..."
815,s816,Movie,The Girl King,2634,"Malin Buska, Sarah Gadon, Michael Nyqvist, Luc...",not available,"June 2, 2021",2015,TV-MA,106 min,"Dramas, International Movies, LGBTQ Movies",Sweden's forward-thinking Queen Kristina resis...
1010,s1011,Movie,Rudra: The Rise of King Pharaoh,2634,"Shailendra Pandey, Rohan, Mukesh Pandey, Bhakt...",not available,"April 20, 2021",2019,TV-Y7,91 min,Children & Family Movies,"When a malicious, resurrected mummy begins to ..."
1071,s1072,Movie,Motu Patlu in Hong Kong: Kung Fu Kings 3,2634,"Saurav Chakraborty, Sankalp Rastogi, Anamaya V...",not available,"April 13, 2021",2017,TV-Y7,84 min,"Children & Family Movies, Music & Musicals",With a dangerous villain to defeat in Hong Kon...
1073,s1074,Movie,Motu Patlu Kung Fu Kings 4 The Challenge of Ku...,2634,"Saurav Chakraborty, Sanket Mhatre, Kamal Chatu...",not available,"April 13, 2021",2018,TV-Y7,86 min,"Children & Family Movies, Music & Musicals","While in Japan, best friends Motu and Patlu ha..."
1120,s1121,Movie,Kingsglaive: Final Fantasy XV,2634,"Aaron Paul, Lena Headey, Sean Bean, Adrian Bou...","Japan, United States","April 1, 2021",2016,PG-13,116 min,"Action & Adventure, Sci-Fi & Fantasy",King Regis of Lucis orders his Kingsglaive war...
1205,s1206,TV Show,The Lost Pirate Kingdom,2634,"James Oliver Wheatley, Sam Callis, Thomas Padl...","United States, United Kingdom","March 15, 2021",2021,TV-MA,1 Season,"Docuseries, Science & Nature TV, TV Action & A...",The real-life pirates of the Caribbean violent...
1593,s1594,TV Show,Kings of Jo'Burg,2634,"Shona Ferguson, Zolisa Xaluva, Tsholofelo Mats...",South Africa,"December 4, 2020",2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",The Masire brothers rule Johannesburg's crimin...
2628,s2629,TV Show,The Last Kingdom,2634,"Alexander Dreymon, Emily Cox, David Dawson, Ia...",United Kingdom,"April 26, 2020",2020,TV-MA,4 Seasons,"British TV Shows, International TV Shows, TV A...",As Alfred the Great defends his kingdom from N...
2665,s2666,TV Show,The King: Eternal Monarch,2634,"Lee Min-ho, Kim Go-eun, Woo Do‑hwan, Kim Kyung...",South Korea,"April 18, 2020",2020,TV-14,1 Season,"Crime TV Shows, International TV Shows, Korean...",A modern-day Korean emperor passes through a m...
2794,s2795,TV Show,The Letter for the King,2634,"Amir Wilson, Ruby Ashbourne Serkis, Thaddea Gr...",United Kingdom,"March 20, 2020",2020,TV-PG,1 Season,"British TV Shows, International TV Shows, TV A...",A young knight in training contends with ancie...
2821,s2822,TV Show,Kingdom,2634,"Ju Ji-hoon, Ryu Seung-ryong, Bae Doona, Kim Sa...","South Korea, United States","March 13, 2020",2020,TV-MA,2 Seasons,"International TV Shows, Korean TV Shows, TV Ac...",While strange rumors about their ill king grip...
3347,s3348,Movie,The King,2634,"Timothée Chalamet, Joel Edgerton, Robert Patti...","United Kingdom, Hungary, Australia","November 1, 2019",2019,R,141 min,Dramas,Wayward Prince Hal must turn from carouser to ...
3553,s3554,TV Show,True and the Rainbow Kingdom,2634,"Michela Luci, Jamie Watson, Anna Claire Bartla...","United States, Canada","August 30, 2019",2019,TV-Y,3 Seasons,Kids' TV,"When something's wrong in the Rainbow Kingdom,..."
3585,s3586,TV Show,The King's Avatar,2634,"Yang Yang, Jiang Shuying, Lai Yumeng, Li Muche...",China,"August 16, 2019",2019,TV-MA,1 Season,"International TV Shows, TV Action & Adventure,...",When an elite gamer is forced out of his profe...
3842,s3843,Movie,Gatao 2: Rise of the King,2634,"Collin Chou, Jason Wang, Jack Kao, Tsai Chen-n...",Taiwan,"May 9, 2019",2018,TV-MA,126 min,"Action & Adventure, Dramas, International Movies",When a zealous gang leader plans to take out a...
4091,s4092,Movie,The Drug King,2634,"Song Kang-ho, Cho Jung-seok, Bae Doona, Kim So...",South Korea,"February 21, 2019",2018,TV-MA,139 min,"Dramas, International Movies, Thrillers",A petty smuggler from Busan dives headfirst in...
4404,s4405,Movie,Outlaw King,2634,"Chris Pine, Aaron Taylor-Johnson, Florence Pug...","United Kingdom, United States","November 9, 2018",2018,R,122 min,"Action & Adventure, Dramas","In 14th-century Scotland, Robert the Bruce cla..."
4480,s4481,Movie,Ronnie Coleman: The King,2634,Ronnie Coleman,United States,"October 25, 2018",2018,TV-MA,93 min,Documentaries,"Today, legendary bodybuilder Ronnie Coleman's ..."
4484,s4485,Movie,Scorpion King 5: Book of Souls,2634,"Zach McGowan, Pearl Thusi, Nathan Jones, Peter...",United States,"October 23, 2018",2018,PG-13,102 min,"Action & Adventure, Sci-Fi & Fantasy",The Scorpion King joins forces with a Nubian p...
4789,s4790,Movie,King of Peking,2634,"Zhao Jun, Wang Naixun, Han Qing, Si Chao, Geng...","China, United States, Australia","July 2, 2018",2018,TV-14,88 min,"Comedies, Dramas, International Movies","Strapped for cash, a traveling projectionist b..."
4838,s4839,TV Show,Dinosaur King,2634,"Megumi Matsumoto, Matsuri Mizuguchi, Tomoko Ko...",Japan,"June 2, 2018",2008,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Aided by tablets found near a downed meteorite...
4879,s4880,TV Show,Kong: King of the Apes,2634,"Lee Tockar, Sam Vincent, Alessandro Juliani, T...","United States, Japan, Canada","May 4, 2018",2018,TV-Y7,2 Seasons,Kids' TV,"In 2050, an evil scientist is about to unleash..."
5084,s5085,Movie,The Polka King,2634,"Jack Black, Jenny Slate, Jason Schwartzman, Ja...",United States,"January 12, 2018",2018,TV-14,94 min,"Comedies, Independent Movies","Determined to make it big in America, Polish-b..."
5138,s5139,TV Show,All Hail King Julien,2634,"Danny Jacobs, Andy Richter, Henry Winkler, Kev...",United States,"December 1, 2017",2017,TV-Y7,5 Seasons,"Kids' TV, TV Comedies",In this Emmy winner for Outstanding Children's...
5344,s5345,Movie,Message from the King,2634,"Chadwick Boseman, Luke Evans, Teresa Palmer, A...","United Kingdom, France, Belgium, United States","August 4, 2017",2017,R,103 min,"Independent Movies, Thrillers",On a relentless quest to avenge his sister's m...
5383,s5384,TV Show,King’s War,2634,"Chen Daoming, Peter Ho, Duan Yihong, Qin Lan, ...",China,"July 7, 2017",2012,TV-14,1 Season,"International TV Shows, TV Dramas","In 210 B.C., during the upheaval following the..."
5475,s5476,Movie,Hasan Minhaj: Homecoming King,2634,Hasan Minhaj,not available,"May 23, 2017",2017,TV-MA,73 min,Stand-Up Comedy,"Comic Hasan Minhaj of ""The Daily Show"" shares ..."
5488,s5489,TV Show,All Hail King Julien: Exiled,2634,"Danny Jacobs, Andy Richter, Kevin Michael Rich...",not available,"May 12, 2017",2017,TV-Y7,1 Season,"Kids' TV, TV Action & Adventure, TV Comedies","Julien's been dethroned, but loyal friends and..."
5511,s5512,Movie,Rodney King,2634,Roger Guenveur Smith,United States,"April 28, 2017",2017,TV-MA,53 min,Dramas,Roger Guenveur Smith gives voice to the man at...
5747,s5748,Movie,Berserk: The Golden Age Arc I - The Egg of the...,2634,"Hiroaki Iwanaga, Takahiro Sakurai, Toa Yukinar...",Japan,"October 15, 2016",2012,TV-MA,77 min,"Action & Adventure, Anime Features, Internatio...",Loner Guts is recruited by Griffith and his ba...
5765,s5766,Movie,Chatô: The King of Brazil,2634,"Marco Ricca, Andrea Beltrão, Letícia Sabatella...",Brazil,"October 1, 2016",2015,TV-MA,105 min,"Dramas, International Movies",The romanticized life of media mogul Assis Cha...
5816,s5817,Movie,Jim Gaffigan: King Baby,2634,Jim Gaffigan,United States,"August 11, 2016",2009,TV-PG,71 min,Stand-Up Comedy,"Jim Gaffigan offers up his take on bacon, bowl..."
5953,s5954,Movie,Joseph: King of Dreams,2634,"Ben Affleck, Mark Hamill, Richard Herd, Mauree...","United States, France, United Kingdom","September 27, 2011",2000,TV-PG,75 min,"Children & Family Movies, Dramas, Faith & Spir...",With his gift of dream interpretation and his ...
6067,s6068,TV Show,A.D. Kingdom and Empire,2634,"Juan Pablo Di Pace, Adam Levy, Chipo Chung, Ba...",United States,"December 15, 2017",2015,TV-14,1 Season,TV Dramas,"In the wake of Jesus Christ's crucifixion, his..."
7070,s7071,Movie,Indiana Jones and the Kingdom of the Crystal S...,2634,"Harrison Ford, Cate Blanchett, Karen Allen, Ra...",United States,"January 1, 2019",2008,PG-13,123 min,"Action & Adventure, Children & Family Movies, ...",Indiana Jones is drawn into a Russian plot to ...
7207,s7208,Movie,King Jack,2634,"Charlie Plummer, Cory Nichols, Christian Madse...",United States,"July 1, 2016",2015,NR,81 min,"Dramas, Independent Movies","Already coping with a bully, a mercurial older..."
7208,s7209,Movie,King's Ransom,2634,"Anthony Anderson, Jay Mohr, Kellita Smith, Nic...","United States, Canada","November 1, 2019",2005,PG-13,98 min,"Action & Adventure, Comedies","A wealthy, despicable businessman comes to the..."
7210,s7211,Movie,Kingpin,2634,"Woody Harrelson, Randy Quaid, Vanessa Angel, B...",United States,"January 1, 2020",1996,PG-13,114 min,"Comedies, Cult Movies, Sports Movies","After a bowler loses his hand, his career take..."
7211,s7212,Movie,Kings,2634,"Halle Berry, Daniel Craig, Lamar Johnson, Kaal...","France, Belgium, China, United States","October 29, 2018",2017,R,87 min,Dramas,A foster mom and her houseful of kids befriend...
7513,s7514,Movie,Motu Patlu: King of Kings,2634,"Saurav Chakrabarty, Vinay Pathak",India,"July 6, 2017",2016,TV-Y7-FV,109 min,"Children & Family Movies, Comedies",Motu and Patlu want to help a circus lion get ...
7595,s7596,Movie,Norm of the North: Keys to the Kingdom,2634,"Andrew Toth, Cole Howard, Maya Kay, Jennifer C...","India, United States","August 21, 2020",2019,TV-PG,92 min,Children & Family Movies,When Norm the polar bear is framed for a crime...
7596,s7597,Movie,Norm of the North: King Sized Adventure,2634,"Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
7689,s7690,TV Show,P. King Duckling,2634,"Marc Thompson, Benjie Randall, Courtney Shaw",United States,"November 7, 2017",2016,TV-Y,1 Season,"Kids' TV, TV Comedies","P. King, the daring but hapless duck, teams up..."
7813,s7814,TV Show,Queens vs. Kings,2634,"Varun Thakur, Anu Menon, Rahul Subramanian, Si...",not available,"October 25, 2018",2018,TV-14,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies","No ""ism"" is left unturned in this celebrity ga..."
8307,s8308,Movie,The Forbidden Kingdom,2634,"Jackie Chan, Jet Li, Collin Chou, Liu Yifei, L...","United States, China","July 1, 2019",2008,PG-13,104 min,"Action & Adventure, Sci-Fi & Fantasy",Jackie Chan and Jet Li star in this rousing ad...
8377,s8378,Movie,The King's Speech,2634,"Colin Firth, Geoffrey Rush, Helena Bonham Cart...","United Kingdom, United States, Australia","June 2, 2018",2010,R,118 min,"Dramas, International Movies","In this biographical drama, Britain's King Geo..."
8404,s8405,Movie,The Lord of the Rings: The Return of the King,2634,"Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mo...","New Zealand, United States","January 1, 2020",2003,PG-13,201 min,"Action & Adventure, Sci-Fi & Fantasy",Aragorn is revealed as the heir to the ancient...
8412,s8413,Movie,The Man Who Would Be Polka King,2634,"Jan Lewan, Greg Korin",United States,"January 12, 2018",2009,TV-14,68 min,"Documentaries, Music & Musicals",This irreverent documentary reveals how charmi...

In [69]:
df[df["description"].str.contains("Family",na=True)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
616,s617,Movie,Working Title,2634,"Hannah Murray, Sosie Bacon, Marianne Rendón, M...",not available,"July 1, 2021",2019,R,110 min,Dramas,"In the '70s, a graduate student works with thr..."
730,s731,Movie,Cobra Kai - The Afterparty,2634,"David Spade, London Hughes, Fortune Feimster",not available,"June 12, 2021",2021,TV-MA,34 min,Movies,"Ralph Macchio, William Zabka and more from the..."
1954,s1955,TV Show,Sneakerheads,2634,"Allen Maldonado, Andrew Bachelor, Jearnest Cor...",United States,"September 25, 2020",2020,TV-MA,1 Season,TV Comedies,Family man Devin falls back into his sneaker o...
2857,s2858,TV Show,Calico Critters Mini Episodes Clover,2634,"Stephanie Sheh, Erika Harlacher, Julie Maddale...",not available,"March 1, 2020",2020,TV-Y,1 Season,Kids' TV,From throwing parties to planning fashion show...
2858,s2859,Movie,Calico Critters: Everyone's Big Dream Flying i...,2634,Erika Harlacher,not available,"March 1, 2020",2019,TV-Y,11 min,Children & Family Movies,"In the Hazelnut Chipmunk Family, Dominic is a ..."
3034,s3035,TV Show,Giri / Haji,2634,"Takehiro Hira, Kelly Macdonald, Yosuke Kubozuk...",United Kingdom,"January 10, 2020",2019,TV-MA,1 Season,"British TV Shows, Crime TV Shows, Internationa...",Family duty sends a lawman to London to look f...
3605,s3606,TV Show,The Family,2634,"James Cromwell, David Rysdahl, Ben Rosenfield,...",United States,"August 9, 2019",2019,TV-14,1 Season,Docuseries,An enigmatic conservative Christian group know...
3718,s3719,Movie,Blood Will Tell,2634,"Oscar Martínez, Dolores Fonzi, Diego Velázquez...","Argentina, United States","June 21, 2019",2019,TV-MA,113 min,"Dramas, Independent Movies, International Movies",Family patriarch Elías begins to unravel after...
4910,s4911,TV Show,Moving On,2634,"Irene Santiago, Gary Estrada, Ariel Rivera, Pa...",not available,"April 27, 2018",2016,TV-PG,1 Season,"International TV Shows, TV Dramas","Family problems, relationship issues and profe..."
5733,s5734,Movie,Norman Lear: Just Another Version of You,2634,"Norman Lear, George Clooney, Bill Moyers, John...",United States,"November 1, 2016",2016,TV-MA,91 min,Documentaries,This documentary turns the spotlight on the ma...
6548,s6549,Movie,Dad,2634,"Jack Lemmon, Ted Danson, Olympia Dukakis, Kath...",United States,"April 1, 2018",1989,PG,117 min,Dramas,Family bonds are revived after a father is dia...

In [70]:
df[df["cast"].str.contains("Steven")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
162,s163,Movie,Marshall,2634,"Chadwick Boseman, Josh Gad, Kate Hudson, Sterl...","United States, China, Hong Kong","September 1, 2021",2017,PG-13,118 min,Dramas,"This biopic of Thurgood Marshall, the first Bl..."
342,s343,Movie,Major Payne,2634,"Damon Wayans, Karyn Parsons, William Hickey, M...",United States,"August 1, 2021",1995,PG-13,97 min,Comedies,A hardened Marine is given his marching orders...
349,s350,Movie,Seabiscuit,2634,"Tobey Maguire, Jeff Bridges, Chris Cooper, Eli...",United States,"August 1, 2021",2003,PG-13,141 min,"Dramas, Sports Movies",An ungainly-looking colt becomes a winning tho...
357,s358,Movie,The Machinist,2634,"Christian Bale, Jennifer Jason Leigh, Aitana S...","Spain, France, United Kingdom, United States","August 1, 2021",2004,R,102 min,"Dramas, Independent Movies, Thrillers",Haunted and gaunt after a prolonged bout of in...
390,s391,TV Show,The Walking Dead,2634,"Andrew Lincoln, Steven Yeun, Norman Reedus, Ch...",United States,"July 26, 2021",2019,TV-MA,10 Seasons,"Classic & Cult TV, TV Action & Adventure, TV D...","In the wake of a zombie apocalypse, survivors ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8608,s8609,Movie,Total Frat Movie,2634,"Justin Deeley, Alex House, Steven Yaffee, Rebe...",United States,"December 19, 2016",2016,NR,94 min,Comedies,A disbanded fraternity tries to get their act ...
8628,s8629,Movie,"Trikal (Past, Present, Future)",2634,"Leela Naidu, Neena Gupta, Anita Kanwar, Soni R...",India,"December 31, 2019",1985,TV-14,134 min,"Comedies, Dramas, Independent Movies","A Goan native returns to his now-derelict, pal..."
8752,s8753,Movie,Wish Man,2634,"Andrew Steel, Kirby Bliss Blanton, Tom Sizemor...",United States,"December 3, 2019",2019,TV-14,108 min,"Children & Family Movies, Dramas","After surviving a life-threatening accident, a..."
8783,s8784,TV Show,Yoko,2634,"Eileen Stevens, Alyson Leigh Rosenfeld, Sarah ...",not available,"June 23, 2018",2016,TV-Y,1 Season,Kids' TV,"Friends Mai, Oto and Vik's games at the park b..."
8784,s8785,Movie,Yoko and His Friends,2634,"Eileen Stevens, Alyson Leigh Rosenfeld, Sarah ...","Russia, Spain","June 23, 2018",2015,TV-Y,78 min,Children & Family Movies,"Vik meets new friends in a new city, where the..."

In [71]:
df[df["country"].str.contains("India",na=True)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4,s5,TV Show,Kota Factory,2634,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
24,s25,Movie,Jeans,2634,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
29,s30,Movie,Paranoia,2634,"Liam Hemsworth, Gary Oldman, Amber Heard, Harr...","United States, India, France","September 19, 2021",2013,PG-13,106 min,Thrillers,"Blackmailed by his company's CEO, a low-level ..."
39,s40,TV Show,Chhota Bheem,2634,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",India,"September 16, 2021",2021,TV-Y7,3 Seasons,Kids' TV,"A brave, energetic little boy with superhuman ..."
50,s51,TV Show,Dharmakshetra,2634,"Kashmira Irani, Chandan Anand, Dinesh Mehta, A...",India,"September 15, 2021",2014,TV-PG,1 Season,"International TV Shows, TV Dramas, TV Sci-Fi &...","After the ancient Great War, the god Chitragup..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8773,s8774,Movie,Yanda Kartavya Aahe,2634,"Ankush Choudhary, Smita Shewale, Mohan Joshi, ...",India,"January 1, 2018",2006,TV-PG,151 min,"Comedies, Dramas, International Movies",Thanks to an arranged marriage that was design...
8775,s8776,TV Show,Yeh Meri Family,2634,"Vishesh Bansal, Mona Singh, Akarsh Khurana, Ah...",India,"August 31, 2018",2018,TV-PG,1 Season,"International TV Shows, TV Comedies","In the summer of 1998, middle child Harshu bal..."
8798,s8799,Movie,Zed Plus,2634,"Adil Hussain, Mona Singh, K.K. Raina, Sanjay M...",India,"December 31, 2019",2014,TV-MA,131 min,"Comedies, Dramas, International Movies",A philandering small-town mechanic's political...
8799,s8800,Movie,Zenda,2634,"Santosh Juvekar, Siddharth Chandekar, Sachit P...",India,"February 15, 2018",2009,TV-14,120 min,"Dramas, International Movies",A change in the leadership of a political part...
8806,s8807,Movie,Zubaan,2634,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

🏆 Challenge Tasks
Find the top 20 oldest movies.
Find all movies released between 2010 and 2020.
Find all TV Shows with rating TV-14.
Find movies directed by the same director more than once.
Find the country with the highest number of Movies.
Find the year in which Netflix added the most content.
Find the longest movie (based on duration).
Create a new column Content_Age:
New → Released after 2020
Recent → 2015–2020
Old → Before 2015
Count content in each Content_Age category.
Export the cleaned dataset as netflix_cleaned.csv.

In [72]:
df[df["type"]=="Movie"].sort_values(by="release_year").head(20)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8205,s8206,Movie,The Battle of Midway,2634,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
8640,s8641,Movie,Tunisian Victory,2634,Burgess Meredith,"United States, United Kingdom","March 31, 2017",1944,TV-14,76 min,"Classic Movies, Documentaries",British and American troops join forces to lib...
7219,s7220,Movie,Know Your Enemy - Japan,2634,"Walter Huston, Dana Andrews",United States,"March 31, 2017",1945,TV-14,63 min,"Classic Movies, Documentaries",Though culturally insensitive by modern standa...
7294,s7295,Movie,Let There Be Light,2634,Walter Huston,United States,"March 31, 2017",1946,TV-PG,58 min,"Classic Movies, Documentaries",Some returning combat veterans suffer scars th...
8587,s8588,Movie,Thunderbolt,2634,"James Stewart, Lloyd Bridges",United States,"March 31, 2017",1947,TV-PG,42 min,"Classic Movies, Documentaries",A P-47 Thunderbolt squadron is shown in prepar...
1699,s1700,Movie,White Christmas,2634,"Bing Crosby, Danny Kaye, Rosemary Clooney, Ver...",United States,"November 15, 2020",1954,TV-G,120 min,"Children & Family Movies, Classic Movies, Come...",Two war buddies fall for two sisters and follo...
2375,s2376,Movie,The Blazing Sun,2634,"Omar Sharif, Faten Hamama, Zaki Rostom, Farid ...",Egypt,"June 18, 2020",1954,TV-14,116 min,"Classic Movies, Dramas, International Movies",Competition between sugar cane producers turns...
7839,s7840,Movie,Rebel Without a Cause,2634,"James Dean, Natalie Wood, Sal Mineo, Jim Backu...",United States,"November 1, 2019",1955,PG-13,111 min,"Classic Movies, Dramas",When Jim Stark arrives in a new town with his ...
7954,s7955,Movie,Scandal in Sorrento,2634,"Vittorio De Sica, Sophia Loren, Lea Padovani, ...","Italy, France","November 13, 2020",1955,TV-PG,93 min,"Classic Movies, Comedies, Independent Movies","When a marshal moves back to his hometown, he ..."
8506,s8507,Movie,The Sign of Venus,2634,"Sophia Loren, Franca Valeri, Vittorio De Sica,...",Italy,"November 13, 2020",1955,TV-14,97 min,"Classic Movies, Comedies, Independent Movies","While suitors swoon over her cousin, a single ..."
2369,s2370,Movie,Dark Waters,2634,"Faten Hamama, Omar Sharif, Ahmed Ramzy, Hussei...",Egypt,"June 18, 2020",1956,TV-14,104 min,"Classic Movies, Dramas, International Movies",A fisherman returns home after a three-year ab...
6784,s6785,Movie,Forbidden Planet,2634,"Leslie Nielsen, Walter Pidgeon, Anne Francis, ...",United States,"November 1, 2019",1956,G,98 min,"Action & Adventure, Classic Movies, Sci-Fi & F...","A pulp-fiction sci-fi classic, Forbidden Plane..."
6853,s6854,Movie,Gigi,2634,"Leslie Caron, Maurice Chevalier, Louis Jourdan...",United States,"November 1, 2019",1958,G,115 min,"Classic Movies, Comedies, Music & Musicals",Gigi's an avant-garde French waif being groome...
6431,s6432,Movie,Cat on a Hot Tin Roof,2634,"Elizabeth Taylor, Paul Newman, Burl Ives, Jack...",United States,"November 1, 2019",1958,NR,108 min,"Classic Movies, Dramas",Members of a Southern clan scramble to curry f...
2368,s2369,Movie,Cairo Station,2634,"Farid Shawqy, Hind Rostom, Youssef Chahine, Ha...",Egypt,"June 18, 2020",1958,TV-14,73 min,"Classic Movies, Dramas, International Movies",A Cairo newsstand vendor's fantasies morph int...
542,s543,Movie,Ujala,2634,"Mala Sinha, Shammi Kapoor, Raaj Kumar, Leela C...",India,"July 6, 2021",1959,TV-14,143 min,"Dramas, International Movies",An honest man dreams of a better life for his ...
6395,s6396,Movie,Butterfield 8,2634,"Elizabeth Taylor, Laurence Harvey, Eddie Fishe...",United States,"November 1, 2019",1960,TV-14,108 min,"Classic Movies, Dramas, Romantic Movies",Elizabeth Taylor won an Oscar as Gloria Wandro...
7637,s7638,Movie,Ocean's Eleven,2634,"Frank Sinatra, Dean Martin, Sammy Davis Jr., P...",United States,"November 1, 2019",1960,TV-PG,127 min,"Action & Adventure, Classic Movies, Comedies",Frank Sinatra leads an all-star cast as Danny ...
5220,s5221,Movie,Singapore,2634,"Shammi Kapoor, Padmini, Maria Menado, Shashika...","India, Malaysia","October 15, 2017",1960,TV-PG,158 min,"Comedies, Dramas, International Movies","When his employee disappears in Singapore, Shy..."
7133,s7134,Movie,Jis Desh Men Ganga Behti Hai,2634,"Raj Kapoor, Padmini, Pran, Chanchal, Lalita Pa...",not available,"December 31, 2019",1960,TV-14,181 min,"Action & Adventure, Dramas, International Movies",Falling in with a band of outlaws during a hol...

In [73]:
df[(df["type"]=="Movie") & (df["release_year"].between(2010,2020))]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
27,s28,Movie,Grown Ups,2634,"Adam Sandler, Kevin James, Chris Rock, David S...",United States,"September 20, 2021",2010,PG-13,103 min,Comedies,Mourning the loss of their beloved junior high...
28,s29,Movie,Dark Skies,2634,"Keri Russell, Josh Hamilton, J.K. Simmons, Dak...",United States,"September 19, 2021",2013,PG-13,97 min,"Horror Movies, Sci-Fi & Fantasy",A family’s idyllic suburban life shatters when...
29,s30,Movie,Paranoia,2634,"Liam Hemsworth, Gary Oldman, Amber Heard, Harr...","United States, India, France","September 19, 2021",2013,PG-13,106 min,Thrillers,"Blackmailed by his company's CEO, a low-level ..."
38,s39,Movie,Birth of the Dragon,2634,"Billy Magnussen, Ron Yuan, Qu Jingjing, Terry ...","China, Canada, United States","September 16, 2021",2017,PG-13,96 min,"Action & Adventure, Dramas",A young Bruce Lee angers kung fu traditionalis...
46,s47,Movie,Safe House,2634,"Denzel Washington, Ryan Reynolds, Vera Farmiga...","South Africa, United States, Japan","September 16, 2021",2012,R,115 min,Action & Adventure,Young CIA operative Matt Weston must get a dan...
...,...,...,...,...,...,...,...,...,...,...,...,...
8791,s8792,Movie,Young Adult,2634,"Charlize Theron, Patton Oswalt, Patrick Wilson...",United States,"November 20, 2019",2011,R,94 min,"Comedies, Dramas, Independent Movies",When a divorced writer gets a letter from an o...
8794,s8795,Movie,اشتباك,2634,"Nelly Karim, Hany Adel, Tarek Abdel Aziz, Ahme...","Egypt, France","October 11, 2018",2016,TV-14,98 min,"Dramas, Independent Movies, International Movies",Amid the tumult following Egyptian President M...
8798,s8799,Movie,Zed Plus,2634,"Adil Hussain, Mona Singh, K.K. Raina, Sanjay M...",India,"December 31, 2019",2014,TV-MA,131 min,"Comedies, Dramas, International Movies",A philandering small-town mechanic's political...
8801,s8802,Movie,Zinzana,2634,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8806,s8807,Movie,Zubaan,2634,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [74]:
df[(df["type"]=="TV Show") & (df["rating"]=="TV-14")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8,s9,TV Show,The Great British Baking Show,2634,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
21,s22,TV Show,Resurrection: Ertugrul,2634,"Engin Altan Düzyatan, Serdar Gökhan, Hülya Dar...",Turkey,"September 22, 2021",2018,TV-14,5 Seasons,"International TV Shows, TV Action & Adventure,...",When a good deed unwittingly endangers his cla...
25,s26,TV Show,Love on the Spectrum,2634,Brooke Satchwell,Australia,"September 21, 2021",2021,TV-14,2 Seasons,"Docuseries, International TV Shows, Reality TV",Finding love can be hard for anyone. For young...
76,s77,TV Show,Yowamushi Pedal,2634,"Daiki Yamashita, Kohsuke Toriumi, Jun Fukushim...",Japan,"September 14, 2021",2013,TV-14,1 Season,"Anime Series, International TV Shows","A timid, anime-loving teen gets drawn into a s..."
82,s83,TV Show,Lucifer,2634,"Tom Ellis, Lauren German, Kevin Alejandro, D.B...",United States,"September 10, 2021",2021,TV-14,6 Seasons,"Crime TV Shows, TV Comedies, TV Dramas","Bored with being the Lord of Hell, the devil r..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8653,s8654,TV Show,Ugly Duckling,2634,"Mook Worranit Thawornwong, Puttichai Kasetsin,...",Thailand,"February 15, 2019",2015,TV-14,4 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Young women face up to their insecurities and ...
8690,s8691,TV Show,Wake Up,2634,"Jag Huang, Chris Wu, Tiffany Hsu, Michael Huan...",not available,"March 31, 2018",2017,TV-14,2 Seasons,"International TV Shows, TV Dramas","After taking the blame for a patient death, an..."
8720,s8721,TV Show,What Happens to My Family,2634,"Settar Tanrıöğen, Uraz Kaygılaroğlu, Berna Kor...",Turkey,"May 5, 2017",2016,TV-14,1 Season,"International TV Shows, TV Comedies, TV Dramas",A naïve young woman goes to Istanbul to meet t...
8721,s8722,TV Show,What Is Love?,2634,"Chris Wu, Jade Chou, Duncan Lai, King Chin, Ki...",Taiwan,"January 1, 2017",2012,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A 32-year-old romantic looking for a long-term...
8736,s8737,TV Show,Who's the One,2634,"Tien Hsin, Weber Yang, Pink Yang, Johnny Lu, A...",Taiwan,"January 1, 2017",2011,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A doctor performs plastic surgery on a fat man...

In [75]:
df["director"].value_counts()[df["director"].value_counts()>1]

director
2634    7972
Name: count, dtype: int64

In [76]:
df["director"].value_counts()>2

director
2634    True
Name: count, dtype: bool

Find the country with the highest number of Movies.

In [77]:
df["country"].value_counts().max()

2482

In [78]:
movie=df[df["type"]=="Movie"] 
movie["country"].value_counts().head(1)

country
United States    1864
Name: count, dtype: int64

Find the year in which Netflix added the most content.
Find the longest movie (based on duration).
Create a new column Content_Age:
    New → Released after 2020
    Recent → 2015–2020
    Old → Before 2015
Count content in each Content_Age category.
Export the cleaned dataset as netflix_cleaned.csv.

In [79]:
df["type"].value_counts()

type
Movie      5656
TV Show    2316
Name: count, dtype: int64

In [80]:
df["release_year"].value_counts().max()

1025

In [81]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [82]:
df["date_added"].value_counts().max()

107

In [118]:
movie=df[df["type"]=="Movie"]


for i in movie["duration"].sort_values(ascending=False):

    if i!="nan":
        
        print(i)
        brack

    else :
        i

99 min

NameError: name 'brack' is not defined

In [122]:
## Create a new column Content_Age:

     # New → Released after 2020
    #  Recent → 2015–2020
    #  Old → Before 2015 


def age(x):
    if x>2020:
        return "new"

    elif x>=2015:
        return "recent"
    else:
        return "old"
    

df["content_age"]=df["release_year"].apply(age)

In [128]:

df[df["content_age"]=="new"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,content_Age,content_age
1,s2,TV Show,Blood & Water,2634,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",new,new
2,s3,TV Show,Ganglands,2634,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",not available,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,new,new
4,s5,TV Show,Kota Factory,2634,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,new,new
5,s6,TV Show,Midnight Mass,2634,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",not available,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...,new,new
6,s7,Movie,My Little Pony: A New Generation,2634,"Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",not available,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,new,new
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,s1469,Movie,What Happened to Mr. Cha?,2634,"Cha In-pyo, Cho Dal-hwan, Song Jae-ryong",South Korea,"January 1, 2021",2021,TV-MA,102 min,"Comedies, International Movies","With the peak of his career long behind him, a...",NaN,new
1551,s1552,TV Show,Hilda,2634,"Bella Ramsey, Ameerah Falzon-Ojo, Oliver Nelso...","United Kingdom, Canada, United States","December 14, 2020",2021,TV-Y7,2 Seasons,Kids' TV,"Fearless, free-spirited Hilda finds new friend...",NaN,new
1696,s1697,TV Show,Polly Pocket,2634,"Emily Tennant, Shannon Chan-Kent, Kazumi Evans...","Canada, United States, Ireland","November 15, 2020",2021,TV-Y,2 Seasons,Kids' TV,After uncovering a magical locket that allows ...,NaN,new
2920,s2921,TV Show,Love Is Blind,2634,"Nick Lachey, Vanessa Lachey",United States,"February 13, 2020",2021,TV-MA,1 Season,"Reality TV, Romantic TV Shows",Nick and Vanessa Lachey host this social exper...,NaN,new
8437,s8438,TV Show,The Netflix Afterparty,2634,"David Spade, London Hughes, Fortune Feimster",United States,"January 2, 2021",2021,TV-MA,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies","Hosts David Spade, Fortune Feimster and London...",NaN,new

Count content in each Content_Age category.
Export the cleaned dataset as netflix_cleaned.csv.

In [131]:
df["content_age"].value_counts()

content_age
recent    4996
old       2482
new        494
Name: count, dtype: int64

In [133]:
df.to_csv("netflix_clean.csv",index=False)

In [138]:
df.drop(columns="content_Age",inplace=True)

In [139]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'content_age'],
      dtype='object')

In [140]:
df.to_csv("netflix_clean.csv",index=False)